name: Build and Deploy to Azure VM

on:
  push:
    branches:
      - main  # or master
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login "${{ secrets.AZURE_CONTAINER_REGISTRY }}" --username "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t "${{ secrets.AZURE_CONTAINER_REGISTRY }}/awesome-python-games:latest" -f docker/Dockerfile .

      - name: Push Docker Image
        run: |
          docker push "${{ secrets.AZURE_CONTAINER_REGISTRY }}/awesome-python-games:latest"

      - name: SSH to Azure VM and Run Container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Pull the latest image from Azure Container Registry
            docker pull "${{ secrets.AZURE_CONTAINER_REGISTRY }}/awesome-python-games:latest"

            # Stop and remove the existing container (if any)
            docker stop awesome-python-games || true
            docker rm awesome-python-games || true

            # Run the new container
            docker run -d --name awesome-python-games -p 80:80 "${{ secrets.AZURE_CONTAINER_REGISTRY }}/awesome-python-games:latest"

